### PR TITLE
Add tests for the config module

### PR DESCRIPTION
**Pull request by nbraud**
That's very basic stuff for now.  :)

### CODE REVIEW

**Comment by duckinator** [comment]
bahhh i accidentally merged things out of order. >.>

**Comment by nbraud** [comment]
@duckinator I rebased the branch, but I don't see CI happening yet  :O

**Comment by nbraud** [comment]
Oh noes, CI is actually broken on Python < 3.4  :sob:

**Comment by astronouth7303** [comment]
Yeah, Python 3.0-3.3 is basically unsupported at this point. What's the need for it?

**Comment by nbraud** [comment]
@astronouth7303 None, probably: it turns out a crucial `pathlib` method is only available starting in 3.5 anyhow...  :(

**Comment by astronouth7303** [comment]
Yeah, debian jessie (oldstable) is 3.4, and stretch (stable) is 3.5.

**Comment by duckinator** [comment]
@nbraud since I merged #15 just now, what's the current state of this?

**Comment by nbraud** [comment]
@duckinator I need to rebase it, and then tests should pass and we can go ahead and merge.  :3

**Comment by nbraud** [comment]
BTW, the rebase wasn't necessary, as Travis ought to re-run the build when the target branch (here, `master`) gets updated; however, Travis doesn't, and I don't exactly feel up to writing some webhook thingamagic to kick it in the pants whenever needed.

**Comment by nbraud** [comment]
Oh, there is an exciting test failure on macOS, but that looks like it might be a `pathlib.Path` bug?  O__o

**Comment by duckinator** [comment]
bors try

**Comment by duckinator** [comment]
bors try

**Comment by duckinator** [comment]
bors retry

**Comment by duckinator** [comment]
bors retry

**Comment by duckinator** [comment]
time to YOLO EVERYTHING

**Pull request merged**
