### PR TITLE
Drop setup.py

### PR DESCRIPTION
**Pull request by nbraud**
Followup on #55.

- [x] Get rid of `setup.py`, which was made optional by pypa/setuptools#1675.
- [x] Set a version requirement for `setuptools`.

### CODE REVIEW

**Comment by nbraud** [comment]
This is blocked on pypa/setuptools#1515, since we to either invoke the `test` and `release` commands, or change the development workflow.

**Comment by duckinator** [comment]
This is also blocked on https://github.com/pypa/pip/issues/6041.

**Comment by duckinator** [comment]
Whoops, didn't mean to close it. >.>

**Comment by duckinator** [comment]
It looks like the [pep517 package](https://pypi.org/project/pep517/) provides this:

```
python3 -m pep517.check path/to/source  # source dir containing pyproject.toml
```

and

```
python -m pep517.build path/to/source  # source dir containing pyproject.toml
```

I think I'll experiment with making a little tool built on top of pep517+twine+the zipapp module which provides a coherent interface for wheel/sdist/zipapp builds and releasing wheel/sdist to pypi.

**Comment by nbraud** [comment]
@duckinator TBH, in the current state of things, the “small tool” could literally be a shell script calling `pep517` and `twine` (though making it in Python will likely be nicer).

**Comment by duckinator** [comment]
@nbraud when you have a moment, could you rebase this? :heart: (no rush, since we can't merge it yet, just would like a more accurate diff to see what the state of it is~)

**Comment by nbraud** [comment]
@duckinator Done; for what it's worth, you could also have done it, since PRs have “Allow edits from maintainers” checked by default, and there couldn't have been any conflict.

**Comment by duckinator** [comment]
Okay, nice, this PR is down to just locking down the setuptools version and removing setup.py like I thought it would be. :3

**Pull request closed without merging**
