### PR TITLE
Add Appveyor to run tests on Windows

### PR DESCRIPTION
**Pull request by nbraud**
I mostly did this on a lark, but I'm kinda curious whether emanate works on Windows.

Feel free to close if you think that testing on silly platforms is a bad idea.  :)

### CODE REVIEW

**Comment by nbraud** [comment]
PS: If Appveyor supports forcing a rebuild of a specific PR, you can make it run the testsuite before merging this, which would save us a “whoops, CI is broken” later.  :3

**Comment by duckinator** [comment]
I'll revisit this PR after getting Travis CI passing + a bit of work on speeding up the test runs.

**Comment by nbraud** [comment]
Okies  :)

**Comment by duckinator** [comment]
@nbraud I realized I could add that myself. :stuck_out_tongue: although tests fail on Windows.

**Comment by duckinator** [comment]
I believe the error is from Windows using backslashes as a path separator. But I'm having trouble determining _where_.

**Comment by nbraud** [comment]
@duckinator There were 2 tests using POSIX-style paths in `emanate.json`. I fixed this.

**Pull request merged**
