### PR TITLE
Cirrus CI: Run tests under Python 3.8-rc (and tolerate failures)

### PR DESCRIPTION
**Pull request by nbraud**

### CODE REVIEW

**Comment by nbraud** [comment]
OK, this fails because prebuilt wheels for `typed-ast` aren't available for CPython 3.8-rc, so it would need a C compiler installed.  :scream_cat:

**Comment by nbraud** [comment]
@duckinator Since `typed-ast` should only be a dependency of the linter, but not of `pytest`, do you think it would make sense to extract linting to a separate task?

**Comment by duckinator** [comment]
@nbraud yeah, that seems reasonable to me. ^^

**Comment by nbraud** [comment]
Whee, CI is green, so let's rebase the yucky `fixup!` away  :)

**Comment by nbraud** [comment]
@duckinator Is it a problem that the linters are run through `lint.sh` rather than a `setup.py` command?
It is possible to define a [custom `distutils` command] , but that's quite cumbersome.

[custom `distutils` command]: https://jichu4n.com/posts/how-to-add-custom-build-steps-and-commands-to-setuppy/

**Comment by duckinator** [comment]
@nbraud I'd _prefer_ a `setup.py` command, but I am okay deferring that and doing it in a similar way to how I did `./setup.py release` (by having a separate library I can pull in, https://github.com/duckinator/distutils_twine )

**Comment by duckinator** [comment]
(That's a big enough task that I'd want it to be done _after_ this PR is merged.)

**Comment by duckinator** [comment]
@nbraud are you happy with this PR? If so, I'll merge it, and start work on the small library for pylint like I did with distutils_twine.

**Pull request merged**
