### PR TITLE
Ci cleanup

### PR DESCRIPTION
**Pull request by duckinator**

### CODE REVIEW

**Comment by duckinator** [comment]
I'm planning to change this to more closely line up with https://github.com/duckinator/bork/pull/237/files so the two projects are a bit more consistent with each other.

**Comment by nbraud** [comment]
LGTM so far  <3

**Comment by nbraud** [comment]
I just rebased it for you, to resolve the merge conflict.

**Comment by nbraud** [comment]
> I'm planning to change this to more closely line up with [Bork](https://github.com/duckinator/bork/pull/237/files) so the two projects are a bit more consistent with each other.

I just did that for you. ^^

**Comment by nbraud** [comment]
Of course now `pip3 install -U .[testing]` is failing on macOS...  >_>'

**Comment by duckinator** [comment]
Whatever the problem was, it looks like it sorted itself out! Thank you for finishing this up for me. :purple_heart: 

bors r+

**Comment by duckinator** [comment]
But why, bors?

**Comment by duckinator** [comment]
bors retry

**Comment by duckinator** [comment]
Turns out bors was confused because it was expecting a task named `CI success`, and using `alias: CI success` wasn't sufficient for that. Switched `alias:` to `name:` and I think we should be good to go. ^.^

bors r+

**Comment by duckinator** [comment]
FreeBSD why are you doing this to me lmao

**Comment by duckinator** [comment]
[ignore this just testing a thing]

**Pull request merged**
