### PR TITLE
Add Cirrus CI support.

### PR DESCRIPTION
**Pull request by duckinator**

### CODE REVIEW

**Comment by ritlew** [comment]
You should squash those commits before merging

**Comment by duckinator** [comment]
Yeah, planning to. This PR is a hot mess, but hopefully Emanate's CI setup will be a bit nicer afterwards. :slightly_smiling_face:

**Comment by duckinator** [comment]
Nice, CI for everything but macOS works on Cirrus, now. Need to get macOS builds working, then clean things up a bit.

**Pull request merged**
