### PR TITLE
Travis: Cache various artefacts

### PR DESCRIPTION
**Pull request by nbraud**
This was requested in #17, but I am not entirely sure how much of a speedup we will get:
- the latest CI build for #17 took 10 minutes (which is seemingly-high);
- the longest-running jobs are the OSX ones, which took almost 5 minutes; there, 4'30" (out of 5') are spent installing the desired Python version;
- the non-OSX jobs take less than 2 minutes, with only ~10s spent running our code.

### CODE REVIEW

**Comment by nbraud** [comment]
The latest build took 8 minutes, with the macOS jobs ([60.6](https://travis-ci.com/duckinator/emanate/jobs/130375364) and [60.7](https://travis-ci.com/duckinator/emanate/jobs/130375365)) taking ~ 5' 30" on average.

The cache should now be populated, let's kick off another build to see if there is an improvement.

**Comment by nbraud** [comment]
Looks like 60b243e is not sufficient, as the current macOS jobs rebuilt Python again.

**Comment by nbraud** [comment]
On a more positive note, we seem to have ~halved the time spent on non-macOS jobs.

**Comment by nbraud** [comment]
Unfortunately, I don't have a macOS environment to poke at the `pyenv` stuff.

**Comment by duckinator** [comment]
@nbraud nice! re: pyenv, I'll see if I can find someone more knowledgeable about OS X and Homebrew stuff to lend a hand. :)

**Comment by duckinator** [comment]
Potential idea based on perusing [the `brew` manpage](https://docs.brew.sh/Manpage):

```
before_install:
  # See <https://github.com/yyuu/pyenv/wiki#suggested-build-environment>
  - [ "$TRAVIS_OS_NAME" == "osx" ] && brew update && brew install openssl readline pyenv
  # Install the desired python version
  - '[ "$TRAVIS_OS_NAME" != "osx" ] || pyenv install $PYENV_VERSION'

  - python --version
  - pip    --version
```

Details:
1. Use `brew install` instead of `brew upgrade` &mdash; I highly doubt wee need the absolute latest version of pyenv. I may be wrong, and have no OS X system to test with.
2. Don't clear the `brew` cache.
3. Since there's only two brew commands, combine them.

TODO:
- [ ] Verify my assumption re №1.
- [ ] Verify clearing the cache is not required.
- [ ] See if there's a way to tell `brew install` to update the cache, thus avoiding the need for a second `brew` command.

**Comment by nbraud** [comment]
@duckinator Looks like `brew install` errors-out when the packages are already installed...
Reverting.

**Comment by duckinator** [comment]
@nbraud try caching `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask` and see if it speeds up `brew update` at all?

That directory is mentioned at https://travis-ci.com/duckinator/emanate/jobs/130651217#L72 but not at https://github.com/nbraud/emanate/blob/d03f7625c18674ef8485877d11e7ac18d659fefc/.travis.yml#L18-L27

**Comment by duckinator** [comment]
@nbraud I also think it may be `$HOME/.pyenv/cache`, not `$HOME/.pyenv_cache`, but I'm not sure of that. (Going off of https://github.com/pyenv/pyenv/blob/v20160310/plugins/python-build/bin/pyenv-install#L180-L184 .)

**Comment by nbraud** [comment]
@duckinator Why are we only caching `~/.pyenv/{cache,versions}` ?

**Comment by nbraud** [comment]
OK, `pyenv rehash` (to regenerate the `pyenv` shims) did the trick.
Smooshing the git history in a sec.

**Comment by nbraud** [comment]
Latest Travis build took 3 minutes (for all 7 jobs).  Looks like we nailed it  :)

**Comment by nbraud** [comment]
@duckinator Caching `.pyenv/shims` is unnecessary, the call to `pyenv rehash` rebuilds it.

**Comment by nbraud** [comment]
@duckinator What is this blocked on?

**Comment by duckinator** [comment]
@nbraud not blocked; was just not at an actual computer for most of the weekend. :) thanks for all of the help!

bors r+

**Pull request merged**
