### PR TITLE
Expose version & authorship information

### LINKED ISSUE #59: Expose version number programmatically
At the moment, there's no way to get version information from Emanate.

This can be solved by doing the following:

1. store the version number as `__version__` in `__init__.py`
2. use this value in setup.cfg (via [the `attr:` directive](https://setuptools.readthedocs.io/en/latest/setuptools.html#specifying-values))
3. use `__version__` to implement `emanate --version`

### PR DESCRIPTION
**Pull request by nbraud**
- [x] Move the author's name and version info to a module-level attribute.
- [x] Implement a `version` command.

Closes #59.

### CODE REVIEW

**Comment by nbraud** [comment]
@duckinator Thanks for documenting this idea; I didn't know about `attr:`, and it neatly fixes an issue I run into with `ppb-vector`: wanting to expose version info programmatically, but not wanting to duplicate it in 2 places, or extract it out of Python code using a yucky regexp in `setup.py`.

**Comment by nbraud** [comment]
Oh, right, you support Python 3.5 so I can't use f-strings  :sob:

**Comment by duckinator** [comment]
@nbraud thanks! Also, two things:

1. You can add yourself to the `__author__` line if you'd like. :heart: (You've easily contributed at least half the code for Emanate lmao)
2. As for the TODO (which is why Lint is failing), yes, it follows semver.

**Comment by nbraud** [comment]
:blush: 

@duckinator I think Python package metadata only support a single author (rude, I know).
It could make sense to:
- document the list of contributors etc. (`CONTRIBUTORS.md` ?)
- set authorship information to something like `The Emanate Authors <emanate@puppy.technology>` if you really don't want single-authorship (and don't mind setting up an email alias).

**Comment by nbraud** [comment]
PS: `emanate@puppy.technology` would be logically followed by `bork@puppy.technology`, which sounds delightful  <3

**Comment by duckinator** [comment]
It does appear that only one author is supported, and afaict there's no way to include contributor information in the metadata, so I think we'll leave it as myself for now and add a contributors file as you suggested.

Currently waiting on #66 to merge so the rest of the PRs that are waiting will go more quickly.

**Pull request merged**
