### PR TITLE
Add automated linting and testing

### PR DESCRIPTION
**Pull request by nbraud**
- [x] Run ~PEP8 checking and~ `pylint`
- [x] Run `pytest`
- [x] Actually write some ~unit~ tests for `pytest`
- [x] Run `flake8` (which includes PEP8 checking)
  - Check syntax & style (default behaviour of `flake8`)
  - Check for trailing commas
  - Check cyclomatic complexity (the number of different paths through a function)
  - Check docstring style
  - Enable the `flake8-bugbear` plugin to get extra lint (and it found a legit bug!)

### CODE REVIEW

**Comment by nbraud** [comment]
@duckinator I think this is mergeable now, and the unit tests can be added individually.
Also, please make it run automatically in whichever CI service you prefer.

**Comment by duckinator** [comment]
nice! thank you very much. ^^

how would I run the tests, once they're added? (so I can set up a script + Travis CI to run it.)

**Comment by astronouth7303** [comment]
Also, the recommended place to keep tests is `tests/test_*.py`

**Comment by nbraud** [comment]
I just rebased this feature branch, and cleaned up the new lint errors that appeared in #5.

**Comment by nbraud** [comment]
@duckinator I added an actual test, and some mew stuff.  I think this is OK to go (modulo adding CI integration)

**Comment by duckinator** [comment]
nice! thanks for the help with this. ^^ :heart:

**Comment by nbraud** [comment]
You are welcome  :D

**Pull request merged**
