### PR TITLE
Try letting bors use compute credits.

### LINKED ISSUE #67: Using CI compute credits
I just realized that #66 likely won't help because of https://github.com/cirruslabs/cirrus-ci-docs/issues/284.

Hoping to find a workaround sometime soon, because it really sucks when CI gets clogged up due to trying to do 24 things at once. :upside_down_face:

### PR DESCRIPTION
**Pull request by duckinator**
Closes #67.

### CODE REVIEW

**Comment by nbraud** [comment]
bors try

**Comment by nbraud** [comment]
Rude  :O

**Comment by duckinator** [comment]
I'm not sure why it won't let you do it -- you are a collaborator on the repo. x_x

bors try

**Comment by duckinator** [comment]
@nbraud turns out they forgot to mention that I need to go to bors.tech and tell it to re-sync permissions. which seems like an important step lmao

**Pull request merged**
