### PR TITLE
Fixup Travis tests

### PR DESCRIPTION
**Pull request by nbraud**

### CODE REVIEW

**Comment by nbraud** [comment]
@duckinator I'm a bit annoyed at Travis, this now has a bunch of horrible hacks in `.travis.yml` to work around them having broken Python support on OSX...

Anyway, the CI now works... and the build failure is a legitimate one: the `directory_tree` test helper is broken on Python 3.4 and earlier.

**Comment by nbraud** [comment]
@duckinator Python 3.4 lacks the `pathlib.Path.expanduser` method, which is important if we want paths relative to a user's homedir to work (i.e. `~/foo` or `~nicoo/foo`).  Do we want to support Py 3.4 regardless?

**Comment by duckinator** [comment]
@nbraud no need to support 3.4 or lower. i personally only need Python 3.6 support. i'm not opposed to supporting 3.5 if somebody else needs it or it Just Happens To Work™.

**Comment by nbraud** [comment]
@duckinator I need it (insofar as I sometimes deploy my dotfiles on Debian stretch boxes) and it already worked, so I updated the list of supported versions in `.travis.yml` and `setup.py`.

**Comment by nbraud** [comment]
@duckinator The build matrix is kinda ugly now (as in, the spreadsheet-like thing under “Checks”) but this is mergeable.

**Comment by duckinator** [comment]
nice, thanks! :3

**Pull request merged**
