### PR TITLE
Cirrus CI: Use Windows container images with Python preinstalled

### PR DESCRIPTION
**Pull request by nbraud**
Contributing back changes I made in https://github.com/ppb/ppb-vector/pull/121 (where I shamelessly copied your Cirrus config)

### CODE REVIEW

**Comment by nbraud** [comment]
@duckinator Looks like I nailed it, but you will have to remove the Windows `PYTHON:3.6.8` and `PYTHON:3.7.2` checks from the list of required status checks (they changed names when I switched to pre-baked Windows containers)

**Comment by duckinator** [comment]
Nice! in `bors.toml` can you change this:

```
  "Windows PYTHON:3.6.8",
  "Windows PYTHON:3.7.2",
```

to this:

```
  "Windows container:python:3.6-windowsservercore-1809",
  "Windows container:python:3.7-windowsservercore-1809",
```

?

That _should_ update bors to understand the changes that were made, meaning that I can merge it normally. :3

**Comment by nbraud** [comment]
@duckinator Thanks, I had missed that (and thought Github was listing them because they were manually configured as required checks)

**Comment by duckinator** [comment]
@nbraud yeah, that is why GitHub was listing them. This was an _additional_ thing. :stuck_out_tongue:

**Pull request merged**
